set  NewSuitePath to  "/Users/ranhesse/desktop" 

set  DAIServer to"https://eval510.dai.eggplant.cloud"
set  DAIusername to "randy.hesse@eggplant.io"
set  DAIpassword to "Spr1ng2016"
//------------------------------
log "Building Suites and Model"
//-----------------------------------------------------
//"Utilities/Framework_Class".ChooseFrameworkType


put new "Utilities/API_Class"  into AC
put new "Utilities/Framework_Class" into FC
put new "Utilities/Json_Class" into JC
put new "Utilities/Suite_Class" into SC

put DAIServer into (AC).DAIServer 
put DAIusername into (AC).username 
put DAIpassword into (AC).password
put DAIusername into (AC).PickedGroup
(AC)."GetAccessToken"
(AC)."GetModels"

put (AC)."ListofModels" into IDModelList
//------
put the number of items of IDModelList into IDModelCount
repeat IDModelCount times
	put item repeatindex() of IDModelList into IDModel
	put IDModel.id into (AC).ModelUID
	//--------------------------
	put (AC)."GetModelJson" into OriginalDAIModel
	//--------------------------
	(FC)."BuildFramework" (OriginalDAIModel)
	put (FC).GetFramework into  (SuiteMapping,JsonMapping)
	//-----------------------------------------------------------------------------------
	(JC)."BuildJson" JsonMapping,OriginalDAIModel
	put (JC).GetJson into  (NewDAIModel)
	//-----------------------------------------------------------------------------------
	(SC).BuildSuite NewSuitePath,SuiteMapping,OriginalDAIModel,NewDAIModel
	(AC).UpdateModel (NewDAIModel) 
	
end repeat

