


//--Build the New Suite in this Location:
put "/Users/ranhesse/desktop" into NewSuitePath


//--Path of the Explorted Json File from Eggplant DAI Suite
put "/Users/ranhesse/Desktop/zivra.json" into ExportedJsonModel



//------------------------------------------
//------------------------------------------
//---Do not Modified Below---------
//------------------------------------------
//------------------------------------------

//--Build the New Suite and the New Model
Utilities.BuildSuite NewSuitePath,ExportedJsonModel