


//--Build the New Suite in this Location:
set  NewSuitePath to  "/Users/pritmodi/desktop/eggPlantAI/" 


//--Path of the Explorted Json File from Eggplant DAI Suite
set ExportedJsonModel to "/Users/pritmodi/Desktop/nopcomm_test.json"


//------------------------------------------
//------------------------------------------
//---Do not Modified Below---------
//------------------------------------------
//------------------------------------------

//--Build the New Suite and the New Model
Utilities.BuildSuite NewSuitePath,ExportedJsonModel