

set  DAIServer to"https://eval510.dai.eggplant.cloud"
set  DAIusername to "randy.hesse@eggplant.io"
set  DAIpassword to "Spr1ng2016"


put new "Utilities/API_Class"  into AC

put DAIServer into (AC).DAIServer 
put DAIusername into (AC).username 
put DAIpassword into (AC).password
(AC)."GetAccessToken"


put "7b004b65-157e-4e3e-83d8-c806577fe7bc" into (AC).ModelUID

put (AC)."GetModelJson" into OriginalDAIModel

log OriginalDAIModel.modeljson.elements